
class KEY(object):
    SERVICE_TIME        = "service_time"
    SERVICE_TYPE        = 'serv_type'
    DEPART_TIME         = 'depart_time'
    ROUTE_ID            = 'route_id'
    TRIP_ID             = 'trip_id'
    HEADSIGN            = 'headsign'
    DIRECTION           = 'direction'
    STOP_ID             = 'stop_id'
    EST_WAIT_SEC        = 'est_wait_sec'
    DISTANCE            = 'dist'
    POPULATION          = 'pop'
    WEIGHT              = 'weight'
    DAILY_DEPARTURES    = 'daily_departures'
    DEPARTURES          = 'departures'

    BAD_ID              = 'bad_id'
    POINT               = 'point'
    NAME                = 'name'
    NOTES               = 'notes'

    STOP_SET            = 'stop_set'
    BUFFER_METHOD       = 'buffer_method'
    SCORE_METHOD        = 'score_method'
    STOP_DEMAND         = 'stop_demand'
    SCORE_NEAREST_ONLY  = 'score_nearest_only'
    DECAY_METHOD        = 'decay_method'
    DECAY_FACTOR        = 'decay_factor'
    DISTANCE_METHOD     = 'distance_method'
    NORMALIZE_VALUE     = 'normalize_value'
    WAIT_BANDPASS       = 'wait_bandpass'

    STOPS_ADDED         = 'stops_added'
    STOPS_REMOVED       = 'stops_removed'
    LAT                 = 'lat'
    LON                 = 'lng'
    LNG                 = 'lng'
